config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :subjects, except: %i[index]
  resources :contents, except: %i[index]
  root 'cats#index'
end

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  belongs_to :subject

  # 記録項目のフォーマットを表すアソシエーション。実際には下記のいずれか一つのみが紐づく。
  has_one :recording_method_multi_level, class_name: 'RecordingMethod::MultiLevel', dependent: :destroy, autosave: true
  has_one :recording_method_binary, class_name: 'RecordingMethod::Binary', dependent: :destroy, autosave: true

  validates :name, presence: true

  def recording_method
    recording_method_multi_level || recording_method_binary
  end
end

app/models/content/form.rb
# frozen_string_literal: true

# パラメータから適切な記録方式のクラスを選択し、Contentとそれに紐づくRecordingMethodを登録する
class Content::Form
  include ActiveRecord::Validations

  def initialize(content, recording_method_params)
    @content = content
    @generator = RecordingMethod::Generator.new(content, recording_method_params)
  end

  def save
    assign_attributes

    if @content.save
      true
    else
      errors.add(:base, error_messages)
      false
    end
  end

  private

  # Contentとそれに紐づくRecordingMethodにパラメータをアサインする
  def assign_attributes
    if @content.persisted?
      attributes = @generator.attributes
      @content.recording_method.assign_attributes(attributes)
    else
      @generator.generate
    end
  end

  def error_messages
    content_errors = @content.errors.map(&:full_message)
    recording_method_errors = @content.recording_method.errors.map(&:full_message)
    content_errors + recording_method_errors
  end
end

app/controllers/contents_controller.rb
# frozen_string_literal: true

class ContentsController < ApplicationController
  before_action :set_content, except: %i[new create]

  def show; end

  def new
    @subject = Subject.find(params[:subject_id])
    @content = @subject.contents.new
    @content_form = Content::Form.new(nil, nil) # エラーメッセージのパーシャルで必要なので置いてるダミーオブジェクト
  end

  def create
    @subject = Subject.find(params[:content][:subject_id])
    @content = Content.new(content_params.merge(subject: @subject))
    @content_form = Content::Form.new(@content, recording_method_params)

    if @content_form.save
      flash.now.notice = I18n.t('contents.successfully_created', content: @content.name)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @content.assign_attributes(content_params)
    @content_form = Content::Form.new(@content, recording_method_params)

    if @content_form.save
      flash.now.notice = I18n.t('contents.successfully_updated', content: @content.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @content.destroy

    flash.now.notice = I18n.t('contents.successfully_destroyed', content: @content.name)
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def content_params
    params.require(:content).permit(:name)
  end

  def recording_method_params
    params.require(:content).permit(
      :recording_method_type, {
        multi_level: %i[left_end_label right_end_label level],
        binary: %i[false_label truth_label]
      }
    )
  end
end

app/views/contents/_content.html.erb
<%= turbo_frame_tag content do %>
  <div style="display: flex">
    <%= content.name %>
    <%= render_recording_method_setting(content) %>
    <%= link_to t('.edit'), edit_content_path(content) %>
    <%= button_to t('.delete'), content, method: :delete %>
  </div>
<% end %>

app/views/contents/_edit_form.html.erb
<%= turbo_frame_tag content do %>
  <%= form_with(model: content) do |form| %>
    <%= render 'validation_error_message', resource: content %>

    <div style="display: flex">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
      <%= render 'recording_methods/form', form: form, form_type: 'edit', recording_method: content.recording_method %>
      <%= form.submit %>
      <%= link_to t('.cancel'), content_path(content) %>
    </div>
  <% end %>
<% end %>

app/views/contents/_new_form.html.erb
<%= turbo_frame_tag "#{subject.id}_new_content" do %>
  <%= form_with(model: content) do |form| %>
    <%= render 'validation_error_message', resource: content_form %>

    <div style="display: flex">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
      <%= render 'recording_methods/form', form: form, form_type: 'new', recording_method: nil %>
      <%= form.hidden_field :subject_id, value: subject.id %>
      <%= form.submit %>
      <%= link_to t('.cancel'), cat_path(subject.cat) %>
    </div>
  <% end %>
<% end %>

app/views/contents/create.turbo_stream.erb
<%= turbo_stream.append "#{@subject.id}_contents", @content %>
<%= turbo_stream.update "#{@subject.id}_new_content" do %>
  <%= link_to t('.new_content'), new_content_path(subject_id: @subject.id)  %>
<% end %>
<%= turbo_stream.update 'flash', partial: 'flash' %>

app/views/contents/destroy.turbo_stream.erb
<%= turbo_stream.remove @content %>
<%= turbo_stream.update 'flash', partial: 'flash' %>

app/views/contents/edit.html.erb
<%= render 'edit_form', content: @content, cat: @cat %>

app/views/contents/new.html.erb
<%= render 'new_form', content: @content, subject: @subject, content_form: @content_form%>

app/views/contents/show.html.erb
<%= render 'content', content: @content %>

app/views/contents/update.turbo_stream.erb
<%= turbo_stream.replace @content %>
<%= turbo_stream.update 'flash', partial: 'flash' %>