config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :subjects, except: %i[index]
  resources :contents, except: %i[index]
  root 'cats#index'
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  belongs_to :cat
  has_many :contents, dependent: :destroy

  validates :name, presence: true
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action :set_subject, except: %i[new create]

  def show; end

  def new
    @cat = Cat.find(params[:cat_id])
    @subject = @cat.subjects.new
  end

  def create
    @cat = Cat.find(params[:subject][:cat_id])
    @subject = @cat.subjects.new(subject_params)

    if @subject.save
      flash.now.notice = I18n.t('subjects.successfully_created', subject: @subject.name)
    else
      render :new, status: :unprocessable_entity, alart: I18n.t('subjects.failed_to_create')
    end
  end

  def edit; end

  def update
    if @subject.update(subject_params)
      flash.now.notice = I18n.t('subjects.successfully_updated', subject: @subject.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @subject.destroy

    flash.now.notice = I18n.t('subjects.successfully_destroyed', subject: @subject.name)
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/views/subjects/_edit_form.html.erb
<%= turbo_frame_tag subject do %>
  <%= form_with(model: subject) do |form| %>
    <%= render 'validation_error_message', resource: subject %>

    <div style="display: flex">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
      <%= form.submit %>
      <%= link_to t('.cancel'), subject_path(subject) %>
    </div>
  <% end %>
<% end %>

app/views/subjects/_new_form.html.erb
<%= turbo_frame_tag 'new_subject' do %>
  <%= form_with(model: subject) do |form| %>
    <%= render 'validation_error_message', resource: subject %>

    <div style="display: flex">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
      <%= form.hidden_field :cat_id, value: cat.id %>
      <%= form.submit %>
      <%= link_to t('.cancel'), cat_path(cat) %>
    </div>
  <% end %>
<% end %>

app/views/subjects/_subject.html.erb
<%= turbo_frame_tag subject do %>
  <div style="display: flex">
    <%= subject.name %>
    <%= link_to t('.edit'), edit_subject_path(subject) %>
    <%= button_to t('.delete'), subject, method: :delete %>
  </div>
<% end %>

app/views/subjects/create.turbo_stream.erb
<%= turbo_stream.append 'subjects', @subject %>
<%= turbo_stream.update 'new_subject' do %>
  <%= link_to t('.new_subject'), new_subject_path(cat_id: @cat.id)  %>
<% end %>
<%= turbo_stream.update 'flash', partial: 'flash' %>

app/views/subjects/destroy.turbo_stream.erb
<%= turbo_stream.remove @subject %>
<%= turbo_stream.update 'flash', partial: 'flash' %>

app/views/subjects/edit.html.erb
<%= render 'edit_form', subject: @subject, cat: @subject.cat %>

app/views/subjects/new.html.erb
<%= render 'new_form', subject: @subject, cat: @cat %>

app/views/subjects/show.html.erb
<%= render 'subject', subject: @subject %>

app/views/subjects/update.turbo_stream.erb
<%= turbo_stream.replace @subject %>
<%= turbo_stream.update 'flash', partial: 'flash' %>