config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :subjects, except: %i[index]
  resources :contents, except: %i[index]
  root 'cats#index'
end

app/models/cat.rb
# frozen_string_literal: true

class Cat < ApplicationRecord
  has_many :subjects, dependent: :destroy

  validates :name, presence: true

  after_create :create_default_subjects

  private

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def create_default_subjects
    subject_1 = subjects.new(name: 'うんち')
    content_1_1 = subject_1.contents.new(name: '量')
    content_1_1.recording_method_multi_level = RecordingMethod::MultiLevel.new(
      left_end_label: '少ない',
      right_end_label: '多い',
      level: 10
    )
    content_1_2 = subject_1.contents.new(name: '毛の有無')
    content_1_2.recording_method_binary = RecordingMethod::Binary.new(
      false_label: '無し',
      truth_label: 'あり'
    )
    subject_2 = subjects.new(name: 'おしっこ')
    content_2_1 = subject_2.contents.new(name: '量')
    content_2_1.recording_method_multi_level = RecordingMethod::MultiLevel.new(
      left_end_label: '少ない',
      right_end_label: '多い',
      level: 10
    )

    transaction { [subject_1, subject_2].each(&:save!) }
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength
end

app/controllers/cats_controller.rb
# frozen_string_literal: true

class CatsController < ApplicationController
  before_action :set_cat, only: %i[show edit update destroy]

  def index
    @cats = Cat.all.order(:created_at)
  end

  def show; end

  def new
    @cat = Cat.new
  end

  def edit; end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      flash.now.notice = I18n.t('cats.successfully_created', cat: @cat.name)
    else
      render :new, status: :unprocessable_entity, alart: I18n.t('cats.failed_to_create')
    end
  end

  def update
    if @cat.update(cat_params)
      flash.now.notice = I18n.t('cats.successfully_updated', cat: @cat.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cat.destroy

    redirect_to cats_path, notice: I18n.t('cats.successfully_destroyed', cat: @cat.name)
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name)
  end
end

app/views/cats/_cat.html.erb
<div style="display: flex">
  <%= cat.name %>
  <%= link_to t('.setting'), cat_path(cat) %>
  <%= button_to t('.delete'), cat, method: :delete %>
</div>

app/views/cats/_cat_setting.html.erb
<%= turbo_frame_tag cat do %>
  <div>
    <%= t('.name', name: cat.name) %>
    <%= link_to t('.edit'), edit_cat_path(cat) %>
  </div>
<% end %>

app/views/cats/_edit_form.html.erb
<%= turbo_frame_tag cat do %>
  <%= form_with(model: cat) do |form| %>
    <%= render 'validation_error_message', resource: cat %>

    <div style="display: flex">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
      <%= form.submit %>
      <%= link_to t('.cancel'), cat_path(cat) %>
    </div>
  <% end %>
<% end %>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/_new_form.html.erb
<%= turbo_frame_tag 'new_cat' do %>
  <%= form_with(model: cat) do |form| %>
    <%= render 'validation_error_message', resource: cat %>

    <div style="display: flex">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
      <%= form.submit %>
      <%= link_to t('.cancel'), cats_path %>
    </div>
  <% end %>
<% end %>

app/views/cats/create.turbo_stream.erb
<%= turbo_stream.append 'cats', @cat %>
<%= turbo_stream.update 'new_cat' do %>
  <%= link_to t('.new_cat'), new_cat_path %>
<% end %>
<%= turbo_stream.update 'flash', partial: 'flash' %>

app/views/cats/edit.html.erb
<%= render 'edit_form', cat: @cat %>

app/views/cats/index.html.erb
<h1><%= t('.title') %></h1>

<div id="cats">
  <% @cats.each do |cat| %>
    <%= render cat %>
  <% end %>
</div>

<%= turbo_frame_tag 'new_cat' do %>
  <%= link_to t('.new_cat'), new_cat_path %>
<% end %>

app/views/cats/new.html.erb
<%= render 'new_form', cat: @cat %>

app/views/cats/show.html.erb
<h1><%= t('.title') %></h1>
<%= render 'cat_setting', cat: @cat %>

<%# 記録対象 %>
<div style="margin-left: 20px">
  <div id="subjects">
    <% @cat.subjects.each do |subject| %>
      <%= render partial: 'subjects/subject', locals: { subject: subject } %>

      <%# 記録項目 %>
      <div style="margin-left: 20px">
        <div id="<%= subject.id %>_contents">
          <% subject.contents.each do |content| %>
            <%= render partial: 'contents/content', locals: { content: content } %>
          <% end %>
        </div>
        <%= turbo_frame_tag "#{subject.id}_new_content" do %>
          <%= link_to t('.new_content'), new_content_path(subject_id: subject.id) %>
        <% end %>
      </div>

    <% end %>
  </div>
  <%= turbo_frame_tag 'new_subject' do %>
    <%= link_to t('.new_subject'), new_subject_path(cat_id: @cat.id) %>
  <% end %>
</div>

<div>
  <%= link_to t('.back_to_cats_page'), cats_path %>
</div>

app/views/cats/update.turbo_stream.erb
<%= turbo_stream.replace @cat do %>
  <%= render 'cat_setting', cat: @cat %>
<% end %>
<%= turbo_stream.update 'flash', partial: 'flash' %>